### ISSUE TITLE
Fastify Support 

### ISSUE THREAD

**Issue by H6LS1S** [flamewow/nestjs-asyncapi#15]
**Is your feature request related to a problem? Please describe.**
Hi, I have long dreamed about of implementing AsyncApi for NestJs and now I found a link to this repository in the NestJs Discord channel. But I had a problem in the bundle: nest + fastify + asyncapi. The fact is that the documentation response is in raw html and is embedded in the `pre` tag and this is probably related to the response header `content-type: text/plain; charset=utf-8`

![image](https://user-images.githubusercontent.com/13855054/132146273-61c45963-82d7-4a2b-879b-7a798402f0ed.png)

**Describe the solution you'd like**
```ts
// asyncapi.module.ts
    httpAdapter.get(finalPath, (req, res) => {
      res.type('html');
      res.send(html)
    });
```

I understand that in the context of the fact that the internal routing of the documentation implies using an express as an adapter and this looks like a crutch, but this is the first thing that came to my mind in 20 minutes of troubleshooting.

![image](https://user-images.githubusercontent.com/13855054/132148194-01a5b7a2-31fd-474c-8087-56a84dc51f06.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by flamewow** [comment]
@H6LS1S Hey, thanks for the reported issue.

Yeah, atm it supports express only. I've done some work to add fastify support, but haven't finalized it. Will try to finish updates shortly and do the release.

**Comment by flamewow** [comment]
@H6LS1S check out https://www.npmjs.com/package/nestjs-asyncapi/v/0.2.0

**Comment by H6LS1S** [comment]
How about a beer this Friday? 🍺  ))
