### ISSUE TITLE
Don't replace AsyncOperationObject's message with another

### ISSUE THREAD

**Issue by skhashaev** [flamewow/nestjs-asyncapi#165]
**Is your feature request related to a problem? Please describe.**
I would like to accept the header name 'authorization', when getting socket.emit messages, so I want to illustrate it in AsyncApi docs

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/16179239/154856218-ff468713-d68f-490d-af9d-5329bddbbea7.png)
I want to be able to choose if I need `message.traits` or not by myself. As solution, you could do
```
export interface AsyncOperationOptions extends Omit<AsyncOperationObject, 'message'> {
    message: Pick<AsyncOperationObject, 'message'> | {
        name: string;
        payload: {
            type: Type<unknown> | Function | [Function] | string;
        };
    }
}
```
or something like that.

**Comment by pavlikm** [comment]
I join to this request. Message, as is defined, is insufficient because of lack o headers definition

**Comment by flamewow** [comment]
hey guys, added headers to the message

see v 0.2.10
