### ISSUE TITLE
enum type is always string

### ISSUE THREAD

**Issue by pavlikm** [flamewow/nestjs-asyncapi#198]
**Describe the bug**
Numeric enum generates type as string

**To Reproduce**
Have given ApiProperty:
```
@ApiPropertyOptional({
        enum: [0, 1, 2],
        example: 1,
        name: "sex",
        enumName: "sex",
        description: "..."
    })
```
In generated schema there is type as string, even if all values, are numbers:
![image](https://user-images.githubusercontent.com/78898602/161911521-9d17e162-318c-4ef0-9899-44b134302bd4.png)

**Expected behavior**
type of enum should be same, as values types (if all values are same type) or from implicit given type from ApiProperty decorator. If I put type: number the result is always string.

**Environment**

Nest version: 8.0.4

**Comment by flamewow** [comment]
@pavlikm hey, enum can't have numeric keys.
`TS2452: An enum member cannot have a numeric name.`
