### ISSUE TITLE
Multiple AsyncApiPub decorators for one method

### ISSUE THREAD

**Issue by koruro** [flamewow/nestjs-asyncapi#26]
**Is your feature request related to a problem? Please describe.**
One class method cannot have multiple AsyncApiPub decorators for multiple events

**Describe the solution you'd like**
Stack multiple @AsyncApiPub(...)

**Comment by flamewow** [comment]
So, you want to be able to assign multiple decorators to method?
Can you give an example where smth like that makes sense?
