### ISSUE TITLE
Bug with displaying payload object fields

### ISSUE THREAD

**Issue by zorin-mv** [flamewow/nestjs-asyncapi#350]
I wrote the code according to the documentation
@AsyncApiSub({
     channel: 'joinGameSession',
     summary: '',
     description: '',
     message: {
       name: 'joinGameSession',
       payload: {
         type: GameSessionRealtimeDto,
       },
     },
   })
By importing my Dto class as a view of the type of the payload that is being received, but going to the asyncApi ui page when trying to open the contents of the object by clicking on the "Expand All" button or clicking on the payload itself or the DTO, nothing happens
![image](https://user-images.githubusercontent.com/78303496/191271345-1a8ce8dc-85e2-4edb-82d3-cb86f6a19de5.png)

**Comment by flamewow** [comment]
helmet adds security headers that are blocking inline scripts
