### ISSUE TITLE
Update @asyncapi/generator to 1.9.11

### ISSUE THREAD

**Issue by nodify-at** [flamewow/nestjs-asyncapi#352]
**Is your feature request related to a problem? Please describe.**
It resolved a critical issue with `fs.exists`. `exists` is unstable and is not compatible with with some libraries where an async hook is used.

**Describe the solution you'd like**
Update to https://github.com/asyncapi/generator/releases/tag/v1.9.11 
I don't expect any side effects since the exists is wrapped and the logic is same.

**Comment by flamewow** [comment]
thanks for heads up, updated and published a new version
