### ISSUE TITLE
 Instead of beautiful documentation, the browser shows html

### ISSUE THREAD

**Issue by NatashkinAlex** [flamewow/nestjs-asyncapi#354]
**Describe the bug**
Instead of beautiful documentation, the browser shows html

**Screenshots**
![image](https://user-images.githubusercontent.com/108875855/191864168-6556ff93-5d8f-4830-bc87-1acc6710b34d.png)

**Environment**

"@nestjs/common": "^9.0.11",
"@nestjs/platform-fastify": "^9.0.11",
"nestjs-asyncapi": "^0.3.2"

 
For Tooling issues:
- Node version: 16.13.2
- Platform:  Mac

**Solution method**
On line 50 in "asyncapi.module.ts" file, replace "html" with "text/html"

**Comment by flamewow** [comment]
@NatashkinAlex thanks for reporting the issue, I've checked out with fastify manual e2e test - was working fine.
I've updated res types to keep in sync with @nestjs/swagger, if you could test on your code or provide a min reproduction repo would be great.
Check out version 0.3.4

**Comment by Natashkinsasha** [comment]
thx, now everything work good
