### ISSUE TITLE
oneOf support

### ISSUE THREAD

**Issue by mdovhopo** [flamewow/nestjs-asyncapi#382]
Hey! Thank you this lib, very good work!

I have a specific use case that i can not really solve with current implementation :( And i wanted to ask if that is fine to add that functionality to the lib.

The use case: 

I send different messages through different channel and type of message is defined by special header, so i cannot really define 1 dto with 1 schema, i would need to use something like `oneOf` thing from json schema. 

Right now the type is like this
```ts
/// ...
  payload: {
      type: Type<unknown> | Function | [Function] | string;
  };
/// ...
```

But instead we could do something like this:

```ts
type PayloadSchema = Type<unknown> | Function | [Function] | string;
/// ...
  payload: {
      type: 
            PayloadSchema | 
            { oneOf: { type: PayloadSchema }[] } |
            { anyOf: { type: PayloadSchema }[] } ; // and so on
  };
/// ...
```

What do you think about this approach?

**Comment by flamewow** [comment]
Thanks, @mdovhopo.
That sounds like a nice improvement, gonna check out how it's done in nestjs/swagger and try to implement a generic approach

**Comment by flamewow** [comment]
I've played a bit with asyncapi playground and what you can do looks like:
```
asyncapi: 2.5.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          feline:
            oneOf:
            - $ref: '#/components/schemas/Cat'
            - $ref: '#/components/schemas/Lion'
  schemas:
    Lion:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer
```
paste into https://studio.asyncapi.com/ to see the results

that can be achieved by having a Dto that has a field with 'oneOf':

```
export class Feline {
  @ApiProperty({
    oneOf: [{ $ref: getSchemaPath(Cat) }, { $ref: getSchemaPath(Lion) }],
  })
  feline: Cat | Lion;
}
```

I'll add that case into the sample app this week

**Comment by mdovhopo** [comment]
Okay, I see thank you for the help 🙀

**Comment by flamewow** [comment]
You can't define `oneOf` on outer level, you need an object where one of the fields can be of `oneOf` type.
