### ISSUE TITLE
Please Add Documentation on How to Use this Lib With Nest Microservice

### ISSUE THREAD

**Issue by ammaroker-r** [flamewow/nestjs-asyncapi#384]
**Is your feature request related to a problem? Please describe.**
The documentation in the README file only covers Nest Applications with WebSocket, and I can't find a way to use this plugin with RabbitMQ and Nest Microservice

**Describe the solution you'd like**
Adding more clear documentation on how to use this lib in various scenarios.

**Describe alternatives you've considered**
N/A

**Comment by flamewow** [comment]
@ammaroker-r I'm working on a major update and a comprehensive sample.

it's gonna be almost identical to WebSockets for rabbitMQ use case: 
mark a controller class with the AsyncApi decorator
mark methods that produce messages
mark methods that consume messages

**Comment by flamewow** [comment]
@ammaroker-r 
I've just released a beta version of the lib with a new API https://www.npmjs.com/package/nestjs-asyncapi/v/1.0.2 , it also contains a sample that covers microservices.
https://github.com/flamewow/nestjs-asyncapi/tree/feat/major_api_changes

please checkout 😃

**Comment by flamewow** [comment]
see the sample app
