### ISSUE TITLE
Multiply object on AsyncApiSub with similar channel name

### ISSUE THREAD

**Issue by Novytskyi-Yevhen** [flamewow/nestjs-asyncapi#387]
**Is your feature request related to a problem? Please describe.**
When i try to add two object to AsyncApiSub with similar channel name, i see just first object on ui

**Describe the solution you'd like**
Two different object in ui

**Describe alternatives you've considered**
Add to channel prefix, and add to description name of chanel

**Additional context**
![image](https://user-images.githubusercontent.com/61864126/197177547-4e69ad1b-e22b-4708-b799-a591e973f03a.png)
![image](https://user-images.githubusercontent.com/61864126/197179415-a6fb23c9-8726-4592-81e8-b4ed432da643.png)

**Comment by flamewow** [comment]
hey @Novytskyi-Yevhen,
2 different objects in UI is not possible, it contradicts the async API protocol. 
One channel can have only one publish and one subscribe operation.
If you want to handle different payloads try oneOf (see https://github.com/flamewow/nestjs-asyncapi/issues/382)

I'm working on a new version that will have a list of updates + extended samples which are gonna give an idea of how to implement it. If you want to get early access (branch still in a draft state, but you can get the idea of how to use oneOf): https://github.com/flamewow/nestjs-asyncapi/tree/feat/new_features

**Comment by Novytskyi-Yevhen** [comment]
@flamewow Thank you man, but it's not that i'm looking. I'll keep that in mind for the future.
