### ISSUE TITLE
old documentation 

### ISSUE THREAD

**Issue by Rebal67** [flamewow/nestjs-asyncapi#420]
**Describe the bug**
the documentation is so old that i couldn't run the package.
the demo example and the sample aren't working.
even after following all the types the documention 

**To Reproduce**
follow the npm documentaion

**Expected behavior**
working documentaion for socket io

**Comment by flamewow** [comment]
@Rebal67 Thanks for reporting

I've double-checked README and found an issue with .addServers, fixed in new version.
Cloned the repo and tried to run sample, haven't faced any issues.
I'm gonna close the issue, please check on your side and reopen if needed
