### ISSUE TITLE
feat: set `AmqpChannelBinding` in generated doc

### ISSUE THREAD

**Issue by getlarge** [flamewow/nestjs-asyncapi#460]
**Is your feature request related to a problem? Please describe.**

It seems that since the release 1.x (i'm currently migrating to it), we cannot generate the `AmqpChannelBinding` but only `AmqpOperationBinding` inside an `AsyncApiOperation`, am i right ?

If yes, have you already planned a way to set the channel bindings ?
If not, could you tell me what i missed ?

**Describe the solution you'd like**
An extra decorator (receiving an array of `AsyncApiChannelBindings` ?) that could be set at the controller or method level could help achieve this by allowing to link a channel name used in Operation with a channel binding.

**Comment by flamewow** [comment]
@getlarge I guess, I've simply missed that capability. Haven't used it for a while and it have gone out of radar.
Can you share how you use it in pre 1.x.x, please?

I have a few ideas, want to check the real-life example to see if those are relevant.

**Comment by getlarge** [comment]
Thanks for the explanation.
Before 1.x.x i was using the `AsyncApiService`decorator to set the channel bindings and the generation ended with a channel description like:

```json
    ...
    "KM_SERVICE.*.identities.created_one": {
      "bindings": {
        "amqp": {
          "is": "queue",
          "queue": {
            "name": "KM_SERVICE",
            ...
          },
          "bindingVersion": "0.2.0"
        }
      },
      "subscribe": {
        "summary": "Created identity event",
        ...,
        "message": {
          "name": "Identity",
          "payload": {
            "$ref": "#/components/schemas/IdentityDto"
          }
        }
      }
    },
    ...
 ```
 
 Now i can "only" set the operation bindings and even though for some unknown reason TS doesn't forbid to use ChannelBindings inside an operation even though the [Operation](https://github.com/flamewow/nestjs-asyncapi/blob/main/lib/interface/asyncapi-common.interfaces.ts#L78) states otherwise... i would like to strictly follow the AsyncAPI specs.

**Comment by flamewow** [comment]
Thanks for sharing @getlarge , I'm gonna take a look at it and do checks shortly

gonna keep you posted regarding the decision

**Comment by flamewow** [comment]
@getlarge I've published beta version https://www.npmjs.com/package/nestjs-asyncapi/v/1.2.0-beta which basically reverts the changes and allows to pass bindings in @AsyncApi decorator

```
@AsyncApi({
  description: 'some description here',
  bindings: {
      amqp: {
        is: 'queue',
        queue: {
          name: 'KM_SERVICE',
        },
        bindingVersion: '0.2.0',
      },
  },
})
```

**Comment by getlarge** [comment]
> @getlarge I've published beta version https://www.npmjs.com/package/nestjs-asyncapi/v/1.2.0-beta which basically reverts the changes and allows to pass bindings in @asyncapi decorator

Excellent, thank you. 
I will try it out on Monday and give some feedback.

**Comment by getlarge** [comment]
@flamewow That solves the issue, thank you.

**Comment by flamewow** [comment]
@getlarge great, gonna merge it into the main branch and do the release 

should be good enough for now, gonna think about more optimal solution to implement in future

**Comment by bar-dagan** [comment]
@flamewow I see that this did not make it into version 1.2.1. It still works in the beta version only. Is there a different solution for this? We are having the same issues as @getlarge did where we need to set the ampq bindings.
