### ISSUE TITLE
Publish on AsyncAPI official doc

### ISSUE THREAD

**Issue by alessandroperetti** [flamewow/nestjs-asyncapi#463]
Hi, 
first of all I would like to thank you for the amazing work you are doing for this great library. 
It's simply amazing!

Are you considering to ask for inserting the lib in the official AsyncAPI docs under tools -> Code-first tools  ([official AsyncAPI docs](https://www.asyncapi.com/docs/tools))
  
It can help you to grow as well as it can help people in finding this library.

Alex

**Comment by flamewow** [comment]
Hey Alex, 
thanks for the cheering words 😃 

Haven't thought about that tbh, thanks for the idea.

P.S. Trento is awesome, being there 1 month ago 😉

**Comment by flamewow** [comment]
https://github.com/asyncapi/website/pull/1354
tracking it there

**Comment by alessandroperetti** [comment]
Great for the PR! WOW! I guess in Trento for skiing :)
