### ISSUE TITLE
NestJS v10 support - ReferenceError: models is not defined

### ISSUE THREAD

**Issue by mipopon** [flamewow/nestjs-asyncapi#488]
**Describe the bug**
NestJS v10 removed some functions from [injector Module](https://github.com/nestjs/nest/blob/v10.0.3/packages/core/injector/module.ts) which causes the nest application to error with

```
    const denormalizedChannels = modules.reduce((channels, { components, metatype, relatedModules, routes }) => {
                                                ^
ReferenceError: models is not defined
```
**To Reproduce**
upgrade nestjs/core to v10

**Expected behavior**
**Environment**

Nest version: 10.0.3
 
For Tooling issues:
- Node version: 18.14.0
- Platform:  Mac

Is someone already working on the upgrade or do you accept a PR?

**Comment by flamewow** [comment]
Thanks for reporting the issue, @mipopon 
I'm planning to work on an update next week

**Comment by flamewow** [comment]
release 1.2.0 that supports nestjs v10
