### ISSUE TITLE
Move puppeteer and typescript to devDependencies to reduce final node_modules drastically

### ISSUE THREAD

**Issue by healdropper** [flamewow/nestjs-asyncapi#513]
**puppeteer**
Info Reasons this module exists
   - "nestjs-asyncapi#@asyncapi#html-template" depends on it
   - Hoisted from "nestjs-asyncapi#@asyncapi#html-template#puppeteer"
   
**typescript**
Info Reasons this module exists
   - Hoisted from "nestjs-asyncapi#@asyncapi#generator#typescript"
 
 It would save around 500 Mb on a final node image if those deps can me moved or do a work around.

Thanks!

**Comment by flamewow** [comment]
Those issues have to be addressed in respective dependency packages
