### ISSUE TITLE
Docs page doesn't show more than 1 `AsyncApiSub` decorator per function

### ISSUE THREAD

**Issue by Mohamedemad4** [flamewow/nestjs-asyncapi#56]
**Describe the bug**
docs page doesn't show  more than 1 sub decorator per function

**To Reproduce**
```
@AsyncApiPub({
    channel: 'start_session',
    summary: 'start a session',
    message: {
        name: 'start session',
        payload: {
            type: startSessionDTO,
        },
    },
})

@AsyncApiSub({
    channel: 'some event that might happen',
    summary: 'event desc',
    message: {
        name: 'event1',
        payload: {
            type: eventDTO
        }
    },
})

@AsyncApiSub({
    channel: 'some OTHER event that might happen',
    summary: 'event 2 desc',
    message: {
        name: 'event2',
        payload: {
            type: event2DTO
        }
    },
})


@SubscribeMessage('start_session')
async startSession(
        @MessageBody() data: startSessionDTO,
        @ConnectedSocket() client: Socket
    ) {
    // do some stuff here
    client.emit(event1)
    // do other stuff
    client.emit(event2)
}
```

**Expected behavior**
I expect to see `event1` and `event2` listed in the docs page.
Instead i only get `start_session` and `event1` in the docs page.
**Note:** defining *filler* (empty functions) between each `@AsyncApiSub` decorator seems to fix the issue.

**Environment**
Nest version: 8.1.1

Check whether this is still an issue in the most recent Nest version
 
For Tooling issues:
- Node version: v16.9.1
- Platform:  Linux

**Comment by flamewow** [comment]
@Mohamedemad4 the guys implemented support of multiple channels in the recent PRs.

Please see https://github.com/flamewow/nestjs-asyncapi/blob/86d0bc387f4afc73da1ba939cfb39ba1e292825e/e2e/src/cats/cats.controller.ts#L22

the decorator can accept multiple channel descriptors

**Comment by Mohamedemad4** [comment]
thank you; closing.
