### ISSUE TITLE
Live preview

### ISSUE THREAD

**Issue by olawalejuwonm** [flamewow/nestjs-asyncapi#562]
Please do you have a live preview of this library.

Am I able to make the request on the page generated by the Async API ?

**Comment by flamewow** [comment]
@olawalejuwonm Hi, we don't have it. But I like the idea, gonna add it soon. 
Thank you.

**Comment by flamewow** [comment]
added live preview
https://flamewow.github.io/nestjs-asyncapi/live-preview/
