### ISSUE TITLE
fix: allow circular references in DTOs

### ISSUE THREAD

**Issue by getlarge** [flamewow/nestjs-asyncapi#72]
Hi, thanks a lot for your effort spent building this library.

**Describe the bug**
I started to declare my existing DTOs (some of them are already used in my OpenAPI specs) and unfortunately i encountered the following issue when running the server and generating AsyncAPI specs :
```
RangeError: Maximum call stack size exceeded
...
```

It happens when we use circular reference in our data models, it seems we can work around that by providing the option `{ dereference: { circular: 'ignore' } }` in [`asyncapi-generator.ts`](https://github.com/flamewow/nestjs-asyncapi/blob/main/lib/services/asyncapi-generator.ts#L42) like mentioned in this [issue](https://github.com/asyncapi/parser-js/issues/83).

**To Reproduce**

1. Create a first `UserDto`
```ts
import { ApiProperty, getSchemaPath } from '@nestjs/swagger';

export class UserDto {
  @ApiProperty({
    description: "User's name",
    required: true,
  })
  username: string;

  @ApiProperty({
    description: "User's companies",
    required: false,
    type: 'array',
    items: {
      oneOf: [{ $ref: getSchemaPath('CompanyDto') }, { type: 'string', format: 'uuid' }],
    },
  })
  companies?: CompanyDto[] | string[];

  @ApiProperty({
    description: "User's assigned companies",
    required: false,
    type: 'array',
    items: {
      oneOf: [{ $ref: getSchemaPath('CompanyDto') }, { type: 'string', format: 'uuid' }],
    },
  })
  assignedCompanies?: CompanyDto[]  | string[];
}

```

2. Create a `CompanyDto`
```ts
import { ApiProperty, getSchemaPath } from '@nestjs/swagger';

export class CompanyDto {
  @ApiProperty({
    description: "Company's name",
    required: true,
  })
  name: string;

  @ApiProperty({
    description: "Company's owner",
    required: true,
    oneOf: [{ $ref: getSchemaPath('UserDto') }, { type: 'string', format: 'uuid' }],
  })
  owner: UserDto  | string;

  @ApiProperty({
    description: "Company's members",
    required: true,
    default: [],
    type: 'array',
    items: {
      oneOf: [{ $ref: getSchemaPath('UserDto') }, { type: 'string', format: 'uuid' }],
    },
  })
  members: UserDto[]  | string[];
}

```

3. Declare UserDto in a service

```ts
  @AsyncApiPub({
    channel: 'READ/USER',
    message: {
      name: 'User',
      payload: {
        type: () => UserDto,
      },
    },
  })
```

**Expected behavior**

We should either be able  :
- to provide circular refs
- to provide a custom configuration to `generateFromString` method

**Edit**
After digging a bit more, it seems the issue comes from asyncapi/parser as handling reference inside oneOf/allOf... is not yet supported. See https://github.com/asyncapi/parser-js/issues/293.

**Comment by flamewow** [comment]
@getlarge thanks for the issue report,
checked the [asyncapi/parser-js#293](https://github.com/asyncapi/parser-js/issues/293) issue, looks like it's resolved in the latest release (1.12.0)

Will check out if it's still an issue on weekends and release new version is it solves the issue.

**Comment by magicmatatjahu** [comment]
@getlarge @flamewow Little update from AsyncAPI team: Yeah, we resolved problem with circular refs in parser-js side, but we still need some work in the react-component -> html-template, and hopefully we will merge all PRs in this week. You can check progress here https://github.com/asyncapi/parser-js/pull/402 Please wait and sorry for problems. Support for circular references when we need to stringify spec took a while 😅

**Comment by getlarge** [comment]
@flamewow @magicmatatjahu thanks for the reply and the news.
I look forward to use this feature!

**Comment by flamewow** [comment]
https://github.com/asyncapi/html-template/pull/286

**Comment by flamewow** [comment]
@getlarge just release new version (with updated html-template).
Please check if you still have an issue.

**Comment by magicmatatjahu** [comment]
If there will be any issues, please ping me in this issue :)
